### ISSUE TITLE
EmbeddedRepositoryExample of org.eclipse.emf.cdo.examples.embedded not working (CDO 4.25)

### ISSUE THREAD

**Issue by Snyfir** [eclipse-cdo/cdo#43]
Hi,

When running EmbeddedRepositoryExample i get NullPointerException the second time when the database already exist.

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.cdo.spi.common.model.InternalCDOPackageInfo.getPackageUnit()" because "packageInfo" is null
	at org.eclipse.emf.cdo.internal.server.Repository.initPackage(Repository.java:2607)
	at org.eclipse.emf.cdo.internal.server.Repository.initSystemPackages(Repository.java:2548)
	at org.eclipse.emf.cdo.server.internal.embedded.EmbeddedRepository.initSystemPackages(EmbeddedRepository.java:80)
	at org.eclipse.emf.cdo.internal.server.Repository.doActivate(Repository.java:2898)
	at org.eclipse.net4j.util.lifecycle.Lifecycle.internalActivate(Lifecycle.java:76)
	at org.eclipse.net4j.util.lifecycle.ShareableLifecycle.internalActivate(ShareableLifecycle.java:43)
	at org.eclipse.net4j.util.lifecycle.Lifecycle.activate(Lifecycle.java:178)
	at org.eclipse.net4j.util.lifecycle.LifecycleUtil.activate(LifecycleUtil.java:146)
	at org.eclipse.net4j.util.lifecycle.LifecycleUtil.activate(LifecycleUtil.java:136)
	at org.eclipse.emf.cdo.server.embedded.CDOEmbeddedRepositoryConfig.activateRepository(CDOEmbeddedRepositoryConfig.java:169)
	at org.eclipse.emf.cdo.server.embedded.CDOEmbeddedRepositoryConfig.doActivate(CDOEmbeddedRepositoryConfig.java:198)
	at org.eclipse.emf.cdo.examples.embedded.CDOFacade.doActivate(CDOFacade.java:119)
	at org.eclipse.net4j.util.lifecycle.Lifecycle.internalActivate(Lifecycle.java:76)
	at org.eclipse.net4j.util.lifecycle.Lifecycle.activate(Lifecycle.java:178)
	at org.eclipse.emf.cdo.examples.embedded.EmbeddedRepositoryExample.main(EmbeddedRepositoryExample.java:28)

**Comment by estepper** [comment]
I've tested this now and it works. I believe that the reported problem has been fixed with commit 0edb71914c046c4fbfd34d8f56fd602dc77cba24 on March 19, 2024. Closing.
